### EXERCISE 1 - Element-wise addition of 2 numpy arrays<br>
Given are 2 similar dimensional numpy arrays, how to get a numpy array output in which every element is an element-wise sum of the 2 numpy arrays?

In [1]:
import numpy as np

a = np.array([[1,2,3],[1,2,3]])
b = np.array([[4,5,6],[4,5,6]])
print(a+b)

[[5 7 9]
 [5 7 9]]


### EXERCISE 2 - Multiplying a matrix (numpy array) by a scalar <br>	
Given a numpy array (matrix), how to get a numpy array output which is equal to the original matrix multiplied by a scalar?

In [2]:
a = np.array([1,2,3])
print(5*a)

[ 5 10 15]


### EXERCISE 3 - Identity Matrix<br>	
Create an identity matrix of dimension 4-by-4

In [3]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### EXERCISE 4 - Array re-dimensioning	<br>
Convert a 1-D array to a 3-D array

### EXERCISE 5 - Array datatype conversion	<br>
Convert all the elements of a numpy array from float to integer datatype

In [4]:
a = np.array([1,2,3])

a.dtype

dtype('int64')

In [5]:
a = a.astype(float)

a.dtype

dtype('float64')

### EXERCISE 6 - Obtaining Boolean Array from Binary Array	<br>
Convert a binary numpy array (containing only 0s and 1s) to a boolean numpy array

In [6]:
a = np.eye(3)

In [7]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
a = a.astype(bool)

a

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

### EXERCISE 7 - Horizontal Stacking of Numpy Arrays	
<br>Stack 2 numpy arrays horizontally i.e., 2 arrays having the same 1st dimension (number of rows in 2D arrays)

In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

### EXERCISE 8 - Vertically Stacking of Numpy Arrays <br>
Stack 2 numpy arrays vertically i.e., 2 arrays having the same last dimension (number of columns in 2D arrays)

In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

### EXERCISE 9 - Custom Sequence Generation	<br>
Generate a sequence of numbers in the form of a numpy array from 0 to 100 with gaps of 2 numbers, for example: 0, 2, 4 ....

In [11]:
list = []
for i in range(0,101,2):
    list.append(i)
numpy_arr = np.array(list)

In [12]:
numpy_arr

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [13]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

### EXERCISE 10 - Getting the positions (indexes) where elements of 2 numpy arrays match <br>
From 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match

In [16]:
a = np.array([1,2,3,4,5])
b = np.array([0,2,3,4,6])

Using for loop:

In [23]:
for i in range(len(a)):
    for j in range(len(b)):
        if a[i]==b[j]:
            idx = i
            print(idx,end=' ')

1 2 3 

Using list comprehension

In [25]:
[i for i in range(len(a)) if a[i]==b[i]]

[1, 2, 3]

### EXERCISE 11 - Generation of given count of equally spaced numbers within a specified range	<br>
Output a sequence of equally gapped 5 numbers in the range 0 to 100 (both inclusive)

In [30]:
a = np.arange(0,101,5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

### EXERCISE 12 - Matrix Generation with one particular value	<br>
Output a matrix (numpy array) of dimension 2-by-3 with each and every value equal to 5

In [35]:
a = (np.ones(6)*5).reshape(2,3)
a

array([[5., 5., 5.],
       [5., 5., 5.]])

### EXERCISE 13 - Array Generation by repeatition of a small array across each dimension <br>
Output an array by repeating a smaller array of 2 dimensions, 10 times

### EXERCISE 14 - Array Generation of random integers within a specified range	<br>
Output a 5-by-5 array of random integers between 0 (inclusive) and 10 (exclusive)

In [37]:
rng = np.random.default_rng()
a = rng.integers(10, size=(5, 5))
a

array([[7, 7, 3, 8, 1],
       [0, 5, 1, 5, 8],
       [1, 4, 8, 2, 0],
       [0, 6, 8, 0, 0],
       [6, 3, 0, 0, 8]])

### EXERCISE 15 - Array Generation of random numbers following normal distribution	<br>
Output a 3-by-3 array of random numbers following normal distribution

### EXERCISE 16 - Matrix Multiplication	<br>
Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array)

In [45]:
a = rng.integers(10, size=(3, 3))
b = rng.integers(10, size=(3, 3))
result = a*b
print(f'Matrix A: {a} \n Matrix B: {b}\n Result: {result}')

Matrix A: [[0 4 4]
 [2 1 1]
 [3 8 3]] 
 Matrix B: [[7 4 9]
 [8 4 2]
 [6 0 6]]
 Result: [[ 0 16 36]
 [16  4  2]
 [18  0 18]]


### EXERCISE 17 - Matrix Transpose	<br>
Output the transpose of a matrix (as numpy array)

In [47]:
a = rng.integers(10, size=(3, 3))
a

array([[4, 7, 9],
       [5, 3, 5],
       [4, 1, 5]])

In [48]:
a.transpose()

array([[4, 5, 4],
       [7, 3, 1],
       [9, 5, 5]])

In [50]:
#Also you can use this for transpose
a.T

array([[4, 5, 4],
       [7, 3, 1],
       [9, 5, 5]])

### EXERCISE 18 - Sine of an Angle (in radians)	<br>
Calculate the sine of an array of angles (in radians) using NumPy

### EXERCISE 19 - Cosine Similarity	<br>
Calculate the cosine similarity of 2 vectors (as numpy arrays)

### EXERCISE 20 - Generating the array element indexes such that the array elements appear in ascending order<br>
Output the array element indexes such that the array elements appear in the ascending order

In [57]:
a = rng.random((3,3))
a

array([[0.20129391, 0.33541159, 0.64793453],
       [0.40922766, 0.9135359 , 0.95332654],
       [0.31316273, 0.89073796, 0.53215531]])

In [59]:
np.sort(a)

array([[0.20129391, 0.33541159, 0.64793453],
       [0.40922766, 0.9135359 , 0.95332654],
       [0.31316273, 0.53215531, 0.89073796]])

In [61]:
b = rng.integers(10, size=(3, 3))
b

array([[9, 0, 6],
       [6, 7, 6],
       [4, 9, 0]])

In [62]:
np.sort(b)

array([[0, 6, 9],
       [6, 6, 7],
       [0, 4, 9]])